name: clickio_consent_sdk
description: "A Flutter plugin for Clickio Consent SDK. Supports iOS and Android."
version: 1.0.0
publish_to: https://pub.dev
homepage: https://clickio.com/
repository: https://github.com/ClickioTech/clickio_consent_sdk_flutter
issue_tracker: https://github.com/ClickioTech/clickio_consent_sdk_flutter/issues

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.clickio.clickio_consent_sdk
        pluginClass: ClickioConsentSdkPlugin
      ios:
        pluginClass: ClickioConsentSdkPlugin   
        podspec: clickio_consent_sdk.podspec 

